// Korean source strings are stable translation keys. Keep placeholders unchanged.
export const english: Record<string, string> = {
  "사용 가능": "Available",
  "✓ 사용 가능": "✓ Available",
  "영상 준비 중…": "Preparing video…",
  "영상을 준비하지 못했습니다. 앱을 다시 열어 주세요.": "Could not prepare the video. Please reopen the app.",
  "이 기능은 운전 보조 기능이며 전방 주시를 대신하지 않습니다. 졸리면 즉시 안전한 곳에 정차하고 쉬세요.": "This assistance feature does not replace watching the road. If sleepy, stop safely and rest.",
  "락스타": "Rock Star",
  "핸들 앞쪽 대시보드와 오른쪽의 두 거치 위치 중 하나를 고르고, 전면 카메라를 얼굴 쪽으로 맞추는 모습": "Choose a dashboard mount ahead of or to the right of the steering wheel, then aim the front camera at your face.",
  "핸들 앞쪽 또는 오른쪽에 고정": "Mount ahead of or to the right of the wheel",
  "도로 시야와 계기판을 가리지 않게 설치해요.": "Keep the road and instrument panel in view.",
  "설정을 저장하지 못했습니다. 확인을 누르면 이번 안내를 닫을 수 있어요.": "Could not save. Tap OK to close this guide for now.",
  "그만 보기를 누르면 다음부터 안내를 숨겨요.": "Don't show again hides this guide next time.",
  "그만 보기": "Don't show again",
  "주행 중에는 조작하지 말고, 졸리면 안전한 곳에서 쉬세요.": "Do not adjust while driving. If sleepy, stop somewhere safe and rest.",
  "두 눈과 얼굴 전체가 보이게": "Keep both eyes and your whole face in frame",
  "카메라 각도는 얼굴 쪽으로": "Angle the front camera toward your face",
  "시야를 가리지 않게 고정": "Mount securely, keep the road in view",
  "거치대에 고정한 휴대폰의 전면 카메라가 운전자의 얼굴을 향하고, 화면 안에 두 눈과 얼굴 전체가 보이는 모습": "A mounted phone with its front camera aimed at the driver, showing both eyes and the whole face in frame.",
  "출발 전, 정차한 상태에서 맞춰 주세요.": "Set up while parked, before you drive.",
  "휴대폰, 이렇게 놓아 주세요": "Position your phone like this",
  "출발 전, 잠깨우기 준비": "Get ready before you drive",
  "잠깨우기 준비 완료!": "Ready to stay alert!",
  "시작을 누르면 5초 기준 측정 후 감지를 시작합니다.": "Press Start to calibrate for 5 seconds and begin detection.",
  "기준 측정 전입니다.": "Not calibrated yet.",
  "설정을 저장하지 못했습니다. 다시 시도해 주세요.": "Could not save settings. Please try again.",
  "화면이나 측정 갱신이 멈춰 카메라를 종료했습니다. 다시 시작해 주세요.": "The display or detection stopped updating. Camera stopped. Please restart.",
  "작은 화면에서 측정을 종료했습니다.": "Detection stopped from the small window.",
  "작은 화면이 닫히거나 앱이 숨겨져 측정을 종료했습니다.": "Detection stopped because the small window closed or the app was hidden.",
  "작은 화면 기능을 불러오지 못했습니다. 최신 APK를 설치해 주세요.": "Could not load picture-in-picture. Please install the latest app.",
  "작은 화면 연결을 확인해 주세요. 앱 화면에서 측정을 계속할 수 있습니다.": "Check the small window connection. Detection can continue in the app.",
  "작은 화면을 열지 못했습니다. Android의 화면 속 화면 허용 설정을 확인해 주세요.": "Could not open the small window. Check Android picture-in-picture permission.",
  "카메라 영상이 멈췄습니다. 카메라를 사용하는 다른 앱을 닫고 다시 시작해 주세요.": "The camera feed stopped. Close other camera apps and try again.",
  "기기 호환 모드로 영상 분석을 다시 준비하고 있습니다…": "Preparing video analysis in compatibility mode…",
  "모바일 Chrome 카메라는 HTTPS 주소에서만 사용할 수 있습니다. 안전한 HTTPS 주소로 다시 접속해 주세요.": "Mobile Chrome requires HTTPS for camera access. Open a secure HTTPS address.",
  "이 브라우저에서는 카메라를 사용할 수 없습니다. HTTPS 또는 설치된 앱에서 실행해 주세요.": "Camera unavailable in this browser. Use HTTPS or the installed app.",
  "카메라 권한 확인 중…": "Checking camera permission…",
  "권한 상태를 확인하지 못했습니다. 앱을 다시 열어 주세요.": "Could not check permissions. Please reopen the app.",
  "카메라 권한이 꺼져 있습니다. ‘권한 확인 및 설정’에서 카메라를 허용해 주세요.": "Camera permission is off. Enable it in Permissions and settings.",
  "카메라 연결 중… 권한 창이 나오면 허용해 주세요.": "Connecting camera… Allow access when prompted.",
  "카메라 연결이 끊어졌습니다. 다른 앱에서 카메라를 사용 중인지 확인한 뒤 다시 시작해 주세요.": "Camera disconnected. Check whether another app is using it, then restart.",
  "카메라 화면을 준비하지 못했습니다.": "Could not prepare the camera view.",
  "카메라 영상 준비 중…": "Preparing camera feed…",
  "카메라 영상 재생이 지연됐습니다. 다른 카메라 앱을 닫고 다시 시작해 주세요.": "Camera startup timed out. Close other camera apps and restart.",
  "졸음 분석 준비 중… 잠시만 기다려 주세요.": "Preparing drowsiness detection… Please wait.",
  "졸음 분석 준비가 지연됐습니다. 감지를 종료하고 다시 시작해 주세요.": "Detection startup timed out. Stop detection and try again.",
  "경고 영상을 재생하지 못했습니다. 카메라 감지는 계속됩니다. 안전한 곳에 정차한 뒤 보관함의 영상 미리보기를 확인해 주세요.": "The warning video could not play. Camera detection continues. Stop safely before checking the preview.",
  "졸음 경고입니다. 안전한 곳에 정차하고 쉬어 주세요.": "Drowsiness warning. Stop in a safe place and take a break.",
  "경고 영상 재생 지연": "Warning video playback timed out",
  "앱이 백그라운드로 전환되어 카메라를 안전하게 종료했습니다. 다시 시작해 주세요.": "Camera stopped because the app moved to the background. Please restart.",
  "화면 방향이 변경되어 카메라를 안전하게 종료했습니다. 현재 방향에서 다시 시작해 기준 위치를 측정해 주세요.": "Camera stopped after a screen rotation. Restart in this orientation to recalibrate.",
  "음성 안내를 재생하지 못했습니다.": "Could not play the voice guidance.",
  "{0} Android 설정에서 한국어 TTS를 확인해 주세요.": "{0} Check text-to-speech in Android settings.",
  "내쉬기": "Breathe out",
  "들이쉬기": "Breathe in",
  "광고 제거가 적용되었습니다. 배너와 전면 광고가 더 이상 표시되지 않습니다.": "Ads removed. Banner and menu interstitial ads are now hidden.",
  "결제를 시작하지 못했습니다.": "Could not start the purchase.",
  "구매 복원을 확인하지 못했습니다.": "Could not restore the purchase.",
  "감지를 종료하고 홈 화면으로 이동할까요?": "Stop detection and return home?",
  "한국어 음성 엔진을 확인하고 있습니다…": "Checking the voice engine…",
  "기본 안내 음성 테스트를 재생했습니다.": "Voice test played.",
  "한국어 음성 엔진을 사용할 수 없습니다.": "The voice engine is unavailable.",
  "{0} Android 설정 → 일반 관리 → 글자 읽어주기에서 한국어 음성을 설치해 주세요.": "{0} Check installed voices in Android text-to-speech settings.",
  "{0} 영상을 받으려면 아래 다운로드 버튼을 눌러 주세요.": "Press Download below to get {0}.",
  "{0} 영상이 현재 적용되어 있습니다.": "{0} is currently applied.",
  "{0} 영상이 졸음 경고에 적용되었습니다.": "{0} is now the warning video.",
  "{0} 영상을 한 번 더 터치하면 적용됩니다.": "Tap {0} again to apply it.",
  "{0} · 현재 적용 영상만 재생합니다.": "{0} · Only the applied video will play.",
  "잠금 해제는 Android 앱에서 광고 시청 후 이용할 수 있어요. 웹에서는 광고 보상을 확인할 수 없어 잠금이 유지됩니다.": "Unlock videos by watching a rewarded ad in the Android app. Unlocking is unavailable in the web preview.",
  "보상형 동영상 광고를 끝까지 시청하면 영상 다운로드가 시작됩니다.": "Watch the entire rewarded ad to download this video.",
  "영상 파일을 받지 못했습니다. 잠금이 유지됩니다.": "Could not download the video. It remains locked.",
  "광고 시청 보상이 확인되지 않아 잠금이 유지됩니다. 광고를 끝까지 본 뒤 다시 시도해 주세요.": "The ad reward was not confirmed. The video remains locked. Watch the full ad and try again.",
  "{0} 잠금 해제 완료 · ‘이 영상으로 설정하기’를 누르면 적용됩니다.": "{0} unlocked · Tap Use this video to apply it.",
  "영상 다운로드 중 문제가 발생했습니다.": "Something went wrong while downloading the video.",
  "열공 경고 영상을 받지 못했습니다.": "Could not download the study warning video.",
  "공부 종료 영상을 받지 못했습니다.": "Could not download the study ending video.",
  "설정 닫고 홈으로": "Close settings and return home",
  "설정 닫고 측정 화면으로": "Close settings and return to detection",
  "이전 화면": "Go back",
  "⚡ 출발 전, 잠깨우기 준비": "⚡ Get ready before you drive",
  "눈 감김 · 고개 움직임 감지 중": "Monitoring eyes and head movement",
  "카메라로 살피는 졸음 신호": "Camera-based drowsiness signals",
  "설정 열기": "Open settings",
  "{0} 선택됨 · 아래 설정 버튼으로 적용해 주세요.": "{0} selected · Use the button below to apply it.",
  "{0} 잠김 · 광고를 끝까지 시청하면 해제됩니다.": "{0} locked · Watch the full ad to unlock it.",
  "졸음 감지": "Drowsiness detection",
  "기준 측정": "Calibrating",
  "감지 중": "Monitoring",
  "연결 중": "Connecting",
  "시작 전": "Ready",
  "홈으로 나가도 작은 화면에서 측정해요.": "Keep monitoring in a small window when you go home.",
  "작은 화면 자동 전환이 꺼져 있어요.": "Automatic picture-in-picture is off.",
  "이 기기는 작은 화면을 지원하지 않아요.": "This device does not support picture-in-picture.",
  "홈 화면 위 작은 창은 Android 앱에서 사용할 수 있어요.": "Picture-in-picture is available in the Android app.",
  "작은 화면으로 보기 ↗": "Open small window ↗",
  "iPhone은 Safari의": "On iPhone, in Safari select",
  "공유 → 홈 화면에 추가": "Share → Add to Home Screen",
  ", Android는 Chrome 메뉴의": ". On Android, in Chrome select",
  "앱 설치": "Install app",
  "를 선택하세요.": ".",
  "자세 교정 카메라": "Posture camera",
  "운전자 카메라": "Driver camera",
  "졸음 경고": "Drowsiness warning",
  "분 측정": "min monitored",
  "기기 내 분석 · 영상 비저장": "On-device analysis · No camera recording",
  "졸음 경고 · 안전한 곳에서 쉬어 가세요": "Drowsiness warning · Stop safely and rest",
  "졸음운전 깨우기 경고 영상": "Drowsiness warning video",
  "눈과 고개가 잘 보이게": "Keep your eyes and head visible",
  "카메라 허용을 기다리고 있습니다": "Waiting for camera permission",
  "자세 교정 준비": "Prepare posture detection",
  "운전자 감지 준비": "Ready to monitor",
  "브라우저의 카메라 권한 창에서 ‘허용’을 선택해 주세요. 허용 후 자동으로 시작합니다.": "Choose Allow in the camera permission prompt. Detection starts after permission is granted.",
  "휴대폰을 고정하고 얼굴부터 허리까지 보이게 맞춰 주세요.": "Secure your phone so your face and torso are visible.",
  "휴대폰을 실제 사용할 위치에 고정하고 현재 각도에서 얼굴이 보이게 해 주세요.": "Secure the phone in its intended position and keep your face visible at this angle.",
  "현재 위치를 유지해 주세요": "Hold your position",
  "얼굴이 보이면 자동으로 시작합니다": "Starts automatically when your face is visible",
  "얼굴·양쪽 어깨·허리선을 화면에 맞춰 주세요": "Keep your face, both shoulders and waist in view",
  "방향과 자세에 관계없이 얼굴만 보여 주세요": "Keep your face visible at any angle",
  "어깨선과 목에서 허리로 이어지는 상체 축을 함께 측정합니다": "Calibrating the shoulders and upper-body axis",
  "정면·사선·측면 어느 방향이든 얼굴이 보이면 시작합니다": "Starts when your face is visible from the front, an angle or the side",
  "졸음운전 감지 상태": "Drowsiness detection status",
  "눈 감김": "Eye closure",
  "고개 숙임": "Head down",
  "지금 나의 상태": "Current status",
  "기준 측정 중": "Calibrating",
  "졸음운전 감지 횟수": "Drowsiness event counts",
  "눈": "Eyes",
  "감김": "closed",
  "정상": "Normal",
  "감지": "Detected",
  "회": "events",
  "고개": "Head",
  "숙임": "down",
  "눈 감김과 고개 숙임이 지속 감지되어 안전 경고 영상을 재생합니다.": "Sustained eye closure and head lowering detected. Playing a safety warning video.",
  "고개 숙임이 지속 감지되어 안전 경고 영상을 재생합니다.": "Sustained head lowering detected. Playing a safety warning video.",
  "눈 감김이 지속 감지되어 안전 경고 영상을 재생합니다.": "Sustained eye closure detected. Playing a safety warning video.",
  "지금 재생 중인 경고 영상": "Warning video playing",
  "경고 영상 재생 방식": "Warning video playback",
  "보유 영상 {0}편 랜덤 재생": "Random from {0} owned videos",
  "재생 중": "Playing",
  "랜덤": "Random",
  "현재 영상만": "Applied only",
  "자세 교정 감지 항목": "Posture detection signals",
  "어깨 기울기": "Shoulder tilt",
  "기준 자세 이탈": "Baseline deviation",
  "눈 깜박임": "Blinks",
  "이번 측정": "This session",
  "숙임 확인 중": "Checking head position",
  "고개 안정": "Head steady",
  "자리 이탈": "Away from seat",
  "자리 확인 필요": "Check seat presence",
  "자리 유지": "Seated",
  "기준 자세 설정 안내": "Position setup guide",
  "기준 자세를 먼저 맞춰요": "Set your position first",
  "휴대폰을 실제 사용할 위치에 고정한 뒤 시작을 누르면, 현재 화면을 기준으로 5초 측정 후 감지를 시작합니다.": "Secure your phone, then press Start. Detection begins after a 5-second calibration at the current angle.",
  "얼굴이 화면 중앙": "Face in the center",
  "눈·고개가 보임": "Eyes and head visible",
  "흔들림 없이 유지": "Keep steady",
  "감지 제어": "Detection controls",
  "감지 종료": "Stop detection",
  "준비 중…": "Preparing…",
  "기준 자세 설정 후 시작": "Calibrate and start",
  "권한 확인 및 설정": "Permissions and settings",
  "확인": "OK",
  "상세 정보 접기": "Hide details",
  "상세 정보 보기": "Show details",
  "눈 상태": "Eye status",
  "/ 기준": "/ baseline",
  "고개 상태": "Head status",
  "3D 앉은 자세": "3D sitting posture",
  "{0}점": "{0} pts",
  "촬영 각도": "Camera angle",
  "어깨 수평": "Shoulder level",
  "상체 축": "Upper-body axis",
  "앞쪽 이동": "Forward movement",
  "3D 추정 신뢰도": "3D confidence",
  "% · 5프레임 흔들림 보정": "% · 5-frame smoothing",
  "졸음·쓰러짐 감지": "Drowsiness and slumping",
  "상체 쓰러짐": "Upper body slumping",
  "상체 안정": "Upper body stable",
  "머리 기울기": "Head tilt",
  "아래쪽 이동": "Downward movement",
  "어깨 수평은 졸음 판정에 사용하지 않습니다.": "Shoulder level is not used to determine drowsiness.",
  "앱 설정": "App settings",
  "설정": "Settings",
  "운전 중에는 조작하지 말고 출발 전에 설정해 주세요.": "Adjust settings before driving. Do not use the screen while driving.",
  "작은 화면 설정을 저장하지 못했습니다.": "Could not save picture-in-picture settings.",
  "작은 화면으로 측정 유지": "Keep monitoring in a small window",
  "측정 중 홈으로 나가면 자동 전환돼요. 창을 닫거나 화면을 끄면 측정이 종료돼요.": "Switches automatically when you go home during detection. Closing the window or turning off the screen stops detection.",
  "Android 8 이상이며 화면 속 화면을 지원하는 기기가 필요해요.": "Requires Android 8 or later and a device supporting picture-in-picture.",
  "Android 앱에서 사용할 수 있어요. 웹에서는 다른 앱으로 이동하면 측정이 종료돼요.": "Available in the Android app. In a browser, detection stops when you switch apps.",
  "켜짐": "On",
  "꺼짐": "Off",
  "앱 전용": "App only",
  "현재 적용 영상만": "Applied video only",
  "· 같은 영상으로 알려요.": "· Use the same video for each warning.",
  "보유 영상 랜덤": "Random owned videos",
  "경고마다 제공된 영상 ": "Randomly choose from",
  "편 중 무작위로 재생해요.": "unlocked videos for each warning.",
  "재생 방식은 감지를 종료한 뒤 변경할 수 있어요.": "Stop detection to change playback settings.",
  "현재 보유 영상이 1편이라 랜덤에서도 같은 영상이 나와요.": "You own one video, so random playback uses the same video.",
  "선택한 방식은 앱을 다시 열어도 유지돼요.": "Your choice is saved when you reopen the app.",
  "카메라·작은 화면 상태를 확인하고 휴대폰 설정으로 이동합니다.": "Check camera and picture-in-picture permissions and open device settings.",
  "열기 ↗": "Open ↗",
  "경보음과 음성 안내": "Warning sound",
  "주의·위험 상태를 한국어로 알립니다.": "Plays a warning tone for caution and danger.",
  "안내 음성 테스트": "Test warning popup and sound",
  "기본 한국어 음성과 TTS 상태를 확인합니다.": "Check the alert sound on this device.",
  "재생": "Play",
  "운전자 기준 재측정": "Recalibrate driver position",
  "얼굴과 자세 기준을 5초간 다시 측정합니다.": "Recalibrate face and posture for 5 seconds.",
  "눈과 고개 움직임 기준을 5초간 다시 측정합니다.": "Recalibrate eyes and head movement for 5 seconds.",
  "재측정": "Recalibrate",
  "홈 화면에 앱 설치": "Add app to home screen",
  "전체 화면에서 빠르게 실행할 수 있습니다.": "Launch quickly in full screen.",
  "설치": "Install",
  "기기 내 개인정보 처리": "On-device privacy",
  "카메라 영상은 서버로 보내거나 저장하지 않습니다. Android에서는 작은 화면이 보이는 동안 측정을 유지하며, 작은 창을 닫거나 화면을 끄면 종료합니다.": "Camera video is not stored or sent to a server. On Android, monitoring continues while the small window is visible and stops when it closes or the screen turns off.",
  "안전 안내": "Safety notice",
  "이 기능은 실험용 보조 장치이며 운전자의 전방 주시를 대신하지 않습니다. 경고가 발생하면 즉시 안전한 곳에 정차하세요.": "This experimental aid does not replace watching the road. If warned, stop immediately in a safe place.",
  "홈으로 돌아가기": "Return home",
  "측정 화면으로 돌아가기": "Return to detection",
  "종료하기": "Stop",
  "위험": "Danger",
  "경고": "Warning",
  "주의": "Caution",
  "영상 경고": "Alerts",
  "시간 흐름 분석": "Session timeline",
  "졸음 신호 흐름": "Drowsiness signals",
  "현재 {0}": "Current: {0}",
  "기록 대기": "Waiting for data",
  "기록": "Recorded",
  "최근 5분 {0} 상태 그래프": "Last 5 minutes: {0} status graph",
  "최근 기록": "Recent activity",
  "측정 전": "Not started",
  "현재": "Now",
  "최근 5분 · 1초 간격": "Last 5 minutes · 1-second samples",
  "감지를 시작하면 정상·주의·경고·위험 변화가 여기에 기록됩니다.": "Start detection to see changes between normal, caution, warning and danger.",
  "광고 제거": "Remove ads",
  "한 번 구매하면 이 기기와 같은 Google Play 계정에서 배너 광고와 메뉴 이동 전면 광고를 표시하지 않습니다.": "A one-time purchase hides banner and menu interstitial ads on this device with the same Google Play account.",
  "구매 상품": "Product",
  "Google Play 결제창을 엽니다.": "Opens Google Play checkout.",
  "결제가 완료되면 구매 토큰을 확인합니다.": "Verifies the purchase token after payment.",
  "검증이 끝나면 광고 제거 상태를 저장하고 광고를 즉시 숨깁니다.": "Saves your purchase and hides ads after verification.",
  "광고 제거가 이미 적용되어 있습니다.": "Ads are already removed.",
  "처리 중…": "Processing…",
  "구매 완료": "Purchased",
  "광고 제거 구매": "Buy ad removal",
  "구매 복원": "Restore purchases",
  "닫기": "Close",
  "더 정확하고 편안한 자세 교정 기능을 준비하고 있습니다.": "Improved posture guidance is being prepared.",
  "편안하게 쉴 수 있는 호흡 안내 기능을 준비하고 있습니다.": "Relaxing breathing guidance is being prepared.",
  "더 정확하고 편안한 수어 통역 기능을 준비하고 있습니다.": "Improved sign language interpretation is being prepared.",
  "현재 준비 중입니다": "Coming soon",
  "안전 운전 약속": "Drive safely",
  "안전하게 시작해요": "Start safely",
  "출발 전에 3가지만 확인해 주세요.": "Check these three things before driving.",
  "휴대폰은 출발 전에 설정해요": "Set up your phone before driving",
  "운전 중에는 화면을 만지지 마세요.": "Do not touch the screen while driving.",
  "졸리면 바로 쉬어가요": "Take a break when sleepy",
  "안전한 곳에 정차하고 충분히 쉬세요.": "Stop safely and get enough rest.",
  "도로와 내 판단이 먼저예요": "Watch the road and use your judgment",
  "앱 알림은 안전운전을 돕는 참고 기능이에요.": "App alerts are only a reference to support safe driving.",
  "확인하고 시작": "Confirm and start",
  "다음에 할게요": "Maybe later",
  "꼭 필독": "Please read",
  "안심하고 이용해 주세요": "Your camera stays private",
  "저희 앱은 카메라로 촬영된 영상을": "Camera video is",
  "저장하거나 서버로 전송하지 않습니다.": "never saved or sent to a server.",
  "영상은": "Video is shown only to check",
  "운전자 상태": "the driver's condition",
  "학습 중 집중 상태": "study focus",
  "를 확인하기 위해 화면에만 표시되며, 별도의 파일로 저장되지 않습니다.": "and is not saved as a separate file.",
  "기기 내에서만 분석": "Analysis stays on your device",
  "카메라 영상 비저장 · 서버 미전송": "No camera recording · No server upload",
  "더 나은 서비스를 제공하기 위해 계속 노력하겠습니다.": "We are working to improve your experience.",
  "확인하고 시작하기": "Confirm and continue",
  "{0} 홈": "{0} home",
  "{0} 영상 보관함": "{0} video library",
  "출발 전, Wake Drive": "Before driving, Wake Drive",
  "오늘도, 열공": "Let's study today",
  "졸음운전 방지 시작": "Start drowsiness detection",
  "열공 모드 시작": "Start studying",
  "적용 중 · {0}": "Applied · {0}",
  "경고 {0} · 종료 {1}": "Warning: {0} · Ending: {1}",
  "열공 모드 영상": "Study videos",
  "열공 경고 영상": "Study warning videos",
  "경고 영상": "Warning video",
  "열공 중 경고 상황이 감지되면 재생됩니다.": "Plays when a warning is detected while studying.",
  "보유": "Owned",
  "적용됨": "Applied",
  "다운로드됨": "Downloaded",
  "선택됨 · 광고로 받기": "Selected · Watch ad to unlock",
  "광고로 받기": "Watch ad to unlock",
  "광고 불러오는 중…": "Loading ad…",
  "적용하기": "Apply",
  "광고 시청 후 다운로드": "Watch ad and download",
  "공부 종료 영상": "Study ending videos",
  "공부를 종료했을 때 재생됩니다.": "Plays when a study session ends.",
  "졸음운전 영상": "Drowsiness videos",
  "졸음운전 모드 중 졸음 현상이 있으면 재생됩니다.": "Plays when drowsiness is detected.",
  "깨우기 영상 목록": "Wake-up videos",
  "한 번 더 터치": "Tap again",
  "새 졸음운전 영상 추후 업데이트 예정": "More drowsiness videos coming soon",
  "새 영상 업데이트 예정": "More videos coming soon",
  "번역 위젯 설정": "Translation widget settings",
  "위젯 설정": "Widget settings",
  "수어 통역 자막의 표시 방법을 기기에 저장합니다.": "Save sign-language subtitle display preferences on this device.",
  "번역 위젯 표시": "Show translation widget",
  "수어 통역 화면 위에 번역 결과를 표시합니다.": "Show translations over the sign-language screen.",
  "표시 위치": "Position",
  "왼쪽 위": "Top left",
  "오른쪽 위": "Top right",
  "왼쪽 아래": "Bottom left",
  "오른쪽 아래": "Bottom right",
  "글자 크기": "Text size",
  "투명도": "Opacity",
  "Gloss 함께 표시": "Show gloss",
  "한국수어 중간 표기를 번역문 위에 표시합니다.": "Show Korean Sign Language gloss above the translation.",
  "표시": "Show",
  "숨김": "Hide",
  "안녕하세요 / 도움": "Hello / Help",
  "무엇을 도와드릴까요?": "How can I help?",
  "준비": "Ready",
  "측정 중": "Measuring",
  "얼굴 확인": "Check face",
  "확인 대기": "Waiting",
  "바른 자세": "Good posture",
  "어깨 기울어짐": "Shoulder tilt",
  "몸 기울어짐": "Leaning",
  "등 굽음": "Slouching",
  "거북목": "Forward head",
  "각도 재측정 필요": "Recalibration needed",
  "허리선 확인": "Check waist visibility",
  "자세 확인": "Check posture",
  "정면": "Front",
  "사선": "Angled",
  "측면": "Side",
  "지속 시간 —": "Duration —",
  "지속 {0}초": "Duration {0}s",
  "카메라 사용 가능 여부 확인 중": "Checking camera availability",
  "시작할 때 카메라 권한을 한 번 요청합니다": "Camera permission is requested when you start",
  "카메라 권한 허용됨": "Camera permission granted",
  "카메라 권한 차단됨 · 주소창의 카메라 설정을 확인하세요": "Camera blocked · Check camera settings in the address bar",
  "이 브라우저에서는 카메라를 사용할 수 없습니다": "Camera unavailable in this browser",
  "HTTPS 접속이 필요합니다": "HTTPS required",
  "출발 전 잠깨우기 안내": "Pre-drive wake-up guide",
  "💥 잠깨우기 준비 완료!": "💥 Ready to stay alert!",
  "경보음과 음성 안내 {0}": "Alert sound and voice guidance: {0}",
  "끄기": "off",
  "켜기": "on",
  "알림": "Alerts",
  "눈 감지 마!!": "Keep your eyes open!",
  "졸음 신호엔": "Stay aware.",
  "깨우기 영상 출동!": "Take a break when tired.",
  "랜덤 재생 준비": "Random playback ready",
  "현재 준비한 영상": "Current video",
  "보유 영상 {0}편": "{0} owned videos",
  "출발 전에 영상과 소리를 확인해요.": "Check alerts before driving.",
  "▶ 효과 재생": "▶ Play effects",
  "Ⅱ 효과 멈춤": "Ⅱ Pause effects",
  "졸음 감지 시작": "Start detection",
  "편": "videos",
  "나를 깨우는": "Choose a",
  "한 편을 골라요.": "wake-up video.",
  "출발 전, 내 스타일의 졸음 경고 영상을 준비해요.": "Prepare your warning video before driving.",
  "⇄ 보유 영상 {0}편 랜덤 재생 중": "⇄ Random playback from {0} owned videos",
  "✓ 현재 적용 영상만 · {0}": "✓ Applied video only · {0}",
  "영상 필터": "Video filter",
  "전체 영상": "All videos",
  "내 보관함": "My library",
  "선택한 경고 영상": "Selected warning video",
  "✓ 현재 적용 중": "✓ Currently applied",
  "지금 선택한 영상": "Selected video",
  "잠금 해제됨": "Unlocked",
  "🔒 잠김": "🔒 Locked",
  "미리보기": "Preview",
  "광고 보고 잠금 해제": "Watch ad to unlock",
  "출발 전에 미리 확인해요.": "Preview before driving.",
  "광고를 끝까지 보면 열려요.": "Watch the full ad to unlock.",
  "졸음 경고 상황에서 재생할 영상": "Video for drowsiness warnings",
  "미리보기 ↗": "Preview ↗",
  "해제 후 미리보기": "Unlock to preview",
  "광고 확인·영상 준비 중…": "Checking reward and preparing video…",
  "✓ 이 영상으로 설정됐어요": "✓ This video is applied",
  "이 영상으로 설정하기": "Use this video",
  "🔒 광고 보고 잠금 해제": "🔒 Watch ad to unlock",
  "영상을 설정하면 ‘현재 적용 영상만’ 재생하도록 바뀝니다.": "Applying a video switches playback to Applied video only.",
  "현재 경고 영상: {0}": "Current warning video: {0}",
  "출발 전 알림 설정": "Pre-drive alert settings",
  "출발 전, 알림 체크": "Check alerts before driving",
  "기기 내 분석": "On-device analysis",
  "주의·위험 상태를 소리로 알려요.": "Sound alerts for caution and danger.",
  "음성 안내 테스트": "Test warning popup and sound",
  "보유 영상 목록": "Owned videos",
  "전체 영상 목록": "All videos",
  "깨우기 영상 컬렉션": "Wake-up video collection",
  "영상 재생": "Play video",
  "잠금 안내": "Unlock information",
  "✓ 경고 영상으로 적용 중": "✓ Applied as warning video",
  "✓ 잠금 해제됨": "✓ Unlocked",
  "🔒 잠긴 영상": "🔒 Locked video",
  "출발 전에 소리와 영상을 확인하세요.": "Check the sound and video before driving.",
  "광고 시청 완료 후 보관함에 추가돼요.": "Added to your library after the ad reward is confirmed.",
  "▶ 미리보기": "▶ Preview",
  "✓ 선택됨": "✓ Selected",
  "이 영상 선택": "Select video",
  "카메라 영상은 기기 안에서 분석해요.": "Camera video is analyzed on your device.",
  "영상 선택과 설정은 출발 전에 마쳐 주세요.": "Finish video selection and setup before driving.",
  "미리보기 닫기": "Close preview",
  "영상을 재생하지 못했습니다. 잠시 후 다시 시도해 주세요.": "Could not play the video. Please try again later.",
  "미리보기는 적용 중인 경고 영상을 변경하지 않습니다.": "Previewing does not change your applied warning video.",
  "운전 참고 정보": "Driving reference information",
  "측정 안 됨": "Not measured",
  "얼굴 인식 중": "Face detected",
  "얼굴 확인 중": "Looking for face",
  "감지 시작 대기": "Waiting to start",
  "측정 시간 {0}분 {1}초": "Session time {0} min {1} sec",
  "시간": "Time",
  "이용 통계 설정": "Usage analytics settings",
  "서비스 개선을 위한 이용 통계": "Usage analytics to improve the service",
  "동의하면 Firebase·Google Analytics로 앱 유입·클릭, 광고 요청·표시·오류·보상 획득, 영상 노출·선택·광고 보상·잠금 해제·시청 시간과 중도 종료, 설정 선호·변경, 감지 시작 결과, 측정 시간을 집계합니다. 앱·기기 정보도 함께 처리됩니다. 카메라 영상, 얼굴 정보, 위치 좌표와 이동 경로는 보내지 않습니다.": "With your consent, Firebase and Google Analytics collect app visits and clicks; ad requests, impressions, errors and rewards; video impressions, selections, unlocks, watch time and early exits; preferences and changes; detection startup results; session duration. App and device information is also processed. Camera video, face information, location coordinates and routes are not sent.",
  "분석 연결 상태를 확인하지 못했습니다.": "Could not check the analytics connection.",
  "Android 앱의 Firebase 연결 후 사용할 수 있습니다.": "Available after Firebase is connected in the Android app.",
  "선택 사항이며 거절해도 모든 기능을 이용할 수 있습니다. 설정에서 언제든 끌 수 있습니다.": "Optional. All features work if you decline. You can turn this off in Settings at any time.",
  "저장 중…": "Saving…",
  "이용 통계 끄기": "Turn analytics off",
  "동의하고 통계 켜기": "Agree and enable analytics",
  "동의하지 않음": "Decline",
  "이미지 준비 중": "Preparing image",
  "현재 위치에서 얼굴만 보이도록 휴대폰 위치를 맞춰 주세요.": "Position the phone so your face is visible.",
  "얼굴, 양쪽 어깨와 허리선이 모두 보이도록 휴대폰 위치를 맞춰 주세요.": "Position the phone so your face, both shoulders and waist are visible.",
  "실제로 사용할 휴대폰 위치에서 얼굴이 보이도록 맞춰 주세요.": "Keep your face visible with the phone in its intended position.",
  "지금 보이는 자세를 그대로 기준으로 저장하고 있습니다.": "Saving your current position as the baseline.",
  "몸을 움직이지 말고 정면을 보세요. 기준 측정을 다시 이어갑니다.": "Keep still and face forward. Calibration will resume.",
  "평소 운전 자세를 유지해 주세요. 현재 보이는 각도를 기준으로 측정합니다.": "Keep your usual driving posture. Calibrating at the current angle.",
  "지금 카메라에 보이는 얼굴 위치를 앞으로의 기준으로 저장하고 있습니다.": "Saving the current face position as the baseline.",
  "{0} 촬영 기준으로 어깨선과 목-허리 상체 축을 잡고 있습니다.": "Calibrating shoulders and torso for the {0} view.",
  "현재 카메라 각도와 눈·고개 위치를 기준으로 잡고 있습니다. 평소 운전 자세를 유지하세요.": "Calibrating the current camera angle, eyes and head. Keep your usual driving posture.",
  "초기 측정한 운전 각도를 정상 기준으로 감지하고 있습니다.": "Monitoring relative to the calibrated driving angle.",
  "초기 측정 각도와 같은 운전 자세입니다.": "Your posture matches the calibrated driving angle.",
  "운전자 얼굴이 보이지 않습니다. 전방과 휴대폰 위치를 확인하세요.": "Your face is not visible. Watch the road and check the phone position when safe.",
  "얼굴을 카메라 중앙에 보여 주세요.": "Keep your face in the center of the camera.",
  "얼굴을 다시 화면에 맞춰 주세요.": "Bring your face back into view.",
  "정상적으로 주시하고 있습니다.": "Your eyes are open.",
  "눈 감김과 고개 숙임이 계속되고 있습니다. 즉시 안전한 곳에 정차하세요.": "Eye closure and head lowering continue. Stop immediately in a safe place.",
  "눈 감김이 3초 이상 지속되고 있습니다. 즉시 눈을 뜨고 안전을 확인하세요.": "Your eyes have been closed for over 3 seconds. Open your eyes and check your safety.",
  "고개 숙임이 3초 이상 지속되고 있습니다. 즉시 고개를 들고 안전을 확인하세요.": "Your head has been down for over 3 seconds. Raise your head and check your safety.",
  "눈 감김과 고개 숙임이 감지됐습니다. 경고가 누적됩니다.": "Eye closure and head lowering detected. Warnings are accumulating.",
  "눈 감김이 2초 이상 감지됐습니다.": "Eye closure detected for over 2 seconds.",
  "고개 숙임이 2초 이상 감지됐습니다.": "Head lowering detected for over 2 seconds.",
  "눈을 뜨고 고개를 들어 주세요.": "Open your eyes and raise your head.",
  "눈을 떠 주세요.": "Open your eyes.",
  "고개를 들어 주세요.": "Raise your head.",
  "눈 감김과 고개 숙임을 확인하고 있습니다.": "Checking eye closure and head position.",
  "기준 촬영 각도와 {0}° 차이입니다. 현재 각도로 다시 측정해 주세요.": "Camera angle differs from baseline by {0}°. Recalibrate at the current angle.",
  "목부터 허리까지 보이도록 카메라 각도를 맞춰 주세요.": "Adjust the camera so your neck and waist are visible.",
  "어깨 높이 차이를 약 {0}° 줄여 수평에 맞추세요.": "Reduce shoulder tilt by about {0}° to level your shoulders.",
  "목에서 허리로 이어지는 상체 축 기울기 {0}°를 기준 자세에 가깝게 맞추세요.": "Adjust the upper-body tilt of {0}° toward your baseline.",
  "상체와 머리 높이를 기준보다 약 {0}% 올리세요.": "Raise your torso and head about {0}% toward your baseline.",
  "머리를 어깨 폭의 약 {0}%만큼 뒤로 당기세요.": "Move your head back by about {0}% of shoulder width.",
  "3D 개인 기준 자세가 안정적입니다.": "Your calibrated 3D posture is stable.",
  "얼굴, 양쪽 어깨와 허리선이 충분히 보이게 카메라를 맞춰 주세요.": "Keep your face, both shoulders and waist clearly visible.",
  "카메라를 시작하지 못했습니다.": "Could not start the camera.",
  "카메라 권한이 꺼져 있습니다. ‘권한 확인 및 설정’ → 앱 설정 → 권한 → 카메라에서 허용해 주세요.": "Camera permission is off. Open Permissions and settings → App settings → Permissions → Camera and allow access.",
  "카메라 권한이 차단됐습니다. Chrome 주소창의 사이트 설정 → 카메라 → 허용으로 바꾼 뒤 다시 시작해 주세요.": "Camera permission is blocked. In Chrome site settings, allow Camera and restart.",
  "카메라를 열지 못했습니다. 다른 카메라 앱을 닫고, 휴대폰 빠른 설정의 ‘카메라 접근’이 켜져 있는지 확인해 주세요.": "Could not open the camera. Close other camera apps and check the device Camera access toggle.",
  "다른 앱이 카메라를 사용 중입니다. 카메라 앱이나 화상회의를 종료한 뒤 다시 시도해 주세요.": "Another app is using the camera. Close camera or video-call apps and try again.",
  "사용 가능한 전면 카메라를 찾지 못했습니다. 기기의 카메라 연결과 앱의 카메라 권한을 확인해 주세요.": "No front camera found. Check the camera connection and app permission.",
  "사용 가능한 전면 카메라를 찾지 못했습니다. 기기의 카메라 연결과 Chrome 권한을 확인해 주세요.": "No front camera found. Check the camera connection and Chrome permission.",
  "카메라 허용을 기다리는 시간이 초과됐습니다. 권한 창에서 허용을 선택한 뒤 다시 시작해 주세요.": "Camera permission timed out. Allow camera access, then try again.",
  "카메라를 시작하지 못했습니다. {0}": "Could not start the camera. {0}",
  "카메라 권한 응답 시간 초과": "Camera permission response timed out",
  "카메라 영상 크기를 확인하지 못했습니다. 앱을 다시 시작해 주세요.": "Could not read the camera dimensions. Please restart the app.",
  "속도 측정 대기": "Waiting for speed",
  "위치 권한 필요": "Location permission required",
  "카메라 영상 프레임이 아직 준비되지 않았습니다.": "Camera frame is not ready yet.",
  "비전 엔진이 아직 준비되지 않았습니다.": "Vision engine is not ready yet.",
  "카메라 영상 크기가 일시적으로 변경되어 분석을 중지했습니다. 휴대폰을 세로로 고정한 뒤 다시 시작해 주세요.": "Analysis stopped after the camera dimensions changed. Hold the phone upright and restart.",
  "영상 분석 엔진에 오류가 발생해 카메라를 중지했습니다. 앱을 다시 시작해 주세요.": "Camera stopped after an analysis engine error. Please restart the app.",
  "일어나요~": "Wake up!",
  "로봇 확성기": "Robot megaphone",
  "골로~갑니당": "Stay awake",
  "천국과지옥": "Heaven and hell",
  "저승사자": "Grim reaper",
  "너구리 안전요원": "Raccoon safety officer",
  "휴게소 안내요정": "Rest stop fairy",
  "졸림공사": "Sleepy works",
  "처녀귀신1편": "Ghost episode 1",
  "동무들~": "Comrades",
  "슈퍼걸": "Supergirl",
  "처음 위치": "Initial position",
  "고개 {0}°": "Head {0}°",
  "어깨 {0}°": "Shoulders {0}°",
  "상체 축 {0}°": "Torso {0}°"
};
